### PR TITLE
feat: Add outputs for bootstrap brokers if SASL access is used

### PR DESCRIPTION
**Pull request by xescab**
This PR simply adds some extra outputs to be used by the calling module. Fee free to add any comemtns.

Thanks!

### CODE REVIEW

**Comment by xescab** [comment]
Hi Angel,

Do yo think this PR could be merged? Do you need me to change some other file?
Please let me know.

Thanks!

**Comment by angelabad** [comment]
Hi, @xescab It looks ok! but I need time to test it.
Thanks!

**Comment by angelabad** [comment]
Hi @xescab , sorry for my late reply. I was very busy! I reviewed your pr, and the idea looks good. But, if the resources arent defined, the value of your outputs is "" (empty string). To avoid errors and confussion, I think if you dont define resources the output should not exists (null). You can see and example ere:

- https://discuss.hashicorp.com/t/is-it-possible-to-display-output-conditionally/2155

Could you please modify your pr?

Thanks for your patience and work!

**Comment by xescab** [comment]
Hi @angelabad , would that work? Thanks!

**Comment by angelabad** [comment]
Hi @xescab , it looks good, I merged and y will release a fix version.

**Pull request merged**
