### PR TITLE
MSK configuration revision not updated in MSK

### PR DESCRIPTION
**Pull request by nsvijay04b1**
This is to fix Issue10- MSK configuration latest revision is not updated correctly in MSK during in-place update.

As there was no dependency, MSK resource & MSK config resource both run parallelly and MSK get latest revision of that time when MSK is started, later when MSK configuration gets a new revision MSK was not aware of . So, created a dependency between MSK-config and MSK , so that MSK will always know correct latest revision.

I tested on my env, please check and approve PR.

### CODE REVIEW

**Review by nsvijay04b1 — COMMENTED** [review]
correction to commit message.  Issue#10 is correct in place of issue#2

**Comment by nsvijay04b1** [comment]
TF log from from env with this fix 

      ~ configuration_info {
            arn      = "arn:aws:kafka:eu-west-1:XXXXXXXXXX:configuration/demonexus-uat-msk-2-6-1/c1307ab1-03ae-4ec5-ae1b-XXXXX-3"
          ~ **revision = 1 -> 2**
        }

**Comment by andormarkus** [comment]
Hi,
`aws_msk_configuration` is still missing the optional `description` field which is available in the provider.
This module does not support external `aws_msk_configuration`.

**Comment by nsvijay04b1** [comment]
> Hi,
> `aws_msk_configuration` is still missing the optional `description` field which is available in the provider.
> This module does not support external `aws_msk_configuration`.

Although not related to the issue, should i handle it ?

**Comment by nsvijay04b1** [comment]
@angelabad @bradonkanyid @victorcmoura @andormarkus

can this PR be approved ?  any issue with it

**Comment by bradonkanyid** [comment]
I'm also in need of this. I'm in support of merging.

**Comment by angelabad** [comment]
Hi, with current code aws_msk_cluste also depends on aws_msk_configuration.this, because it uses:
```
configuration_info {
    arn      = aws_msk_configuration.this.arn
    revision = aws_msk_configuration.this.latest_revision
}
```

Please see comment on #10

Thanks for your contribution!

**Pull request closed without merging**
